---
title: "Minutes from meeting with Carl Schwatz"
author: "Catarina Wor"
date:  "11th of Nobember 2021"
output: bookdown::html_document2
---



# Meeting Attendees

Carl Schwartz, Nick Komick, Rob Houtman, Catarina Wor

# General meeting conclusions

In general Carl seemed supportive of the idea of using a hierarchical model to improve the iRec model calibration. He also proposed the use of a smoothing model, a CAR model to smooth the catch estimates from both creel and iRec. 

"small area methods" and hierarchical models are te same thing.

We agreed that the best strategy would be to follow the following steps:

1. Design the second generation Irec calibration model with raw data
 This model will be a hierarchical model considering area as hierarchical effect and month/season/time period as a smoothed effect (GAM). 
 Error in iREC and creel (latent variables) will be characterized by sampling the data and re-fitting the model multiple times. 

2. Produce smoothed catch estimates for both irec and creel. This smoothing model would be done with a CAR model. The objective would be to produce better estimates of catches in areas with low sampling. 
For a CAR model an adjacency matrix is required. Determining proximity in between areas is not sraightforward as areas that are close geographically may have very different fisher populations. E.g. two areas on either side of the north area of Vancouver Island.
- need to check if adjacency marix can be composed of just 0s and 1s. 




3. Re fit the Irec calibration model on the smoothed estimates. Compare steps 3 and 1 and determine what is the best procedure for catch estimation. 








